use ad;
INSERT INTO ad_category(ad_id, category_id) values(1,1);
INSERT INTO ad_category(ad_id, category_id) values(2,2);
INSERT INTO ad_category(ad_id, category_id) values(3,1);
INSERT INTO ad_category(ad_id, category_id) values(4,1);
INSERT INTO ad_category(ad_id, category_id) values(5,2);
INSERT INTO ad_category(ad_id, category_id) values(6,1);
INSERT INTO ad_category(ad_id, category_id) values(7,1);
INSERT INTO ad_category(ad_id, category_id) values(8,2);
INSERT INTO ad_category(ad_id, category_id) values(9,3);
INSERT INTO ad_category(ad_id, category_id) values(10,2);
INSERT INTO ad_category(ad_id, category_id) values(11,2);
INSERT INTO ad_category(ad_id, category_id) values(12,2);
INSERT INTO ad_category(ad_id, category_id) values(13,1);
INSERT INTO ad_category(ad_id, category_id) values(14,1);
INSERT INTO ad_category(ad_id, category_id) values(15,1);
INSERT INTO ad_category(ad_id, category_id) values(16,1);
INSERT INTO ad_category(ad_id, category_id) values(17,2);
INSERT INTO ad_category(ad_id, category_id) values(18,2);
INSERT INTO ad_category(ad_id, category_id) values(19,3);
INSERT INTO ad_category(ad_id, category_id) values(20,1);

