# ad seeder
use ad;
insert into ads (title, description, user_id) values ('red rider bb gun', 'don\'t shoot your eye out',1);
insert into ads (title, description, user_id) values ('legos - eiffel tower', 'I\'m sure at least 99% of the legos are here!',2);
insert into ads (title, description, user_id) values ('brand new car', 'new car, low miles, dont ask questions',2);
insert into ads (title, description, user_id) values ('macbook', 'looking to write code? this thing is a beast!',3);
insert into ads (title, description, user_id) values ('slippers', 'my grandma\'s old slippers',3);
insert into ads (title, description, user_id) values ('dresser', 'full victorian style dresser, definitely NOT from ikea',3);
insert into ads (title, description, user_id) values ('van', 'comes with free thunder unicorn mural on side',4);
insert into ads (title, description, user_id) values ('couch', 'with queen pullout sleeper, needs cleaning, must pick up',5);
insert into ads (title, description, user_id) values ('housekeeper needed', '10$/hr clean my house!',5);
insert into ads (title, description, user_id) values ('cheap sunglasses', 'nightwear only recommended',6);
insert into ads (title, description, user_id) values ('basketball', 'swish swish swish',6);
insert into ads (title, description, user_id) values ('catdog', 'canceled because it scared me',6);
insert into ads (title, description, user_id) values ('hot dog water', 'mmmmmmmm',6);
insert into ads (title, description, user_id) values ('one headphone', 'left or right, you choose',7);
insert into ads (title, description, user_id) values ('ping pong balls', 'red cups not included',7);
insert into ads (title, description, user_id) values ('fire', 'mans greatest invention',8);
insert into ads (title, description, user_id) values ('beer', 'beer tastes good',8);
insert into ads (title, description, user_id) values ('shoes, size 15', 'possibly owned by Shaq',9);
insert into ads (title, description, user_id) values ('I NEED MY GRASS CUT', 'have mower, will pay',10);
insert into ads (title, description, user_id) values ('room for rent', '4 walls, floor creaks',10);